version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "github-actions"
    # Groups all github-actions updates into a single PR
    groups:
      github-actions:
        patterns:
          - "*"